### ISSUE TITLE
LWP::Simple does not pull down entire page.

### ISSUE THREAD

**Issue by ronaldxs** [cosimo/perl6-lwp-simple#10]
It looks from the code like it is just pulling down one packet.  For example if you

perl6 -MLWP::Simple -e 'say LWP::Simple.get("http://perlcabal.org/syn/S02.html");'

you just get back the top of the page.  I am tempted to add this as test case with a match on something at the bottom of the page to verify we pulled the whole thing.

Ron

**Comment by cosimo** [comment]
We have a few tests about this issue now and they all pass as of current master.
