### ISSUE TITLE
No such method 'bytes' for invocant of type 'Str'

### ISSUE THREAD

**Issue by ronaldxs** [cosimo/perl6-lwp-simple#15]
The above error now comes out for the current version of rakudo because the Str object no longer supports the .bytes method and IO::Socket::INET.recv() returns a string not a buffer.  A hacky fix just changing .bytes to .chars might work but it may be better to use read() rather than recv() to get back a byte oriented buffer or wait for some planned parrot changes that may allow recv to return a buffer again.  I am currently working on a read() based solution to this.

**Comment by cosimo** [comment]
... time passes ...

Works now, so I'll just close this.
