### ISSUE TITLE
Tests abort with "Could not parse chunk header"

### ISSUE THREAD

**Issue by moritz** [cosimo/perl6-lwp-simple#19]
Several tests abort with

    Could not parse chunk header
      in method parse_chunks at lib/LWP/Simple.pm:177
      in method make_request at lib/LWP/Simple.pm:215
      in method request_shell at lib/LWP/Simple.pm:63
      in method post at lib/LWP/Simple.pm:32
      in block  at t/custom-headers-and-content.t:10

on Rakudo 2012.09

**Comment by cosimo** [comment]
Works with current master and perl6 2015.09
