### ISSUE TITLE
get-w3-redirect.t failing

### ISSUE THREAD

**Issue by zengargoyle** [cosimo/perl6-lwp-simple#41]
I'm guessing the http://jigsaw.w3.org/HTTP/300/301.html url in the test is now being redirected to a https url?  This was from a fresh 'rakudobrew build moar; rakudobrew build panda; panda install Task::Star`.

==> Testing LWP::Simple
t/000-load-module.t ............. ok
t/basic-auth.t .................. ok
t/custom-headers-and-content.t .. ok
t/get-binary-camelia.t .......... ok
t/get-chunked-6guts.t ........... ok
t/get-perl6-org.t ............... ok
t/get-unsized.t ................. ok
t/get-w3-latin1-utf8.t .......... ok
501 Protocol scheme 'https' is not supported  <URL:https://jigsaw.w3.org/HTTP/300/Overview.html>
  in method request_shell at lib/LWP/Simple.pm:40
  in block  at lib/LWP/Simple.pm:84
  in method request_shell at lib/LWP/Simple.pm:68
  in method get at lib/LWP/Simple.pm:28
  in block <unit> at t/get-w3-redirect.t:7
t/get-w3-redirect.t ............. 
No subtests run 
t/getstore.t .................... ok
t/parse-url.t ................... ok
t/socket-sanity.t ............... ok
t/stringify-headers.t ........... ok
Test Summary Report
-------------------
t/get-w3-redirect.t           (Wstat: 0 Tests: 0 Failed: 0)
  Parse errors: No plan found in TAP output
Files=13, Tests=54, 10 wallclock secs ( 0.03 usr  0.00 sys +  5.04 cusr  0.27 csys =  5.34 CPU)
Result: FAIL

**Comment by cosimo** [comment]
It seems to work with current master. Please can you confirm?
