### ISSUE TITLE
Build failing with rakudo 2015.03

### ISSUE THREAD

**Issue by tbrowder** [cosimo/perl6-lwp-simple#48]
The following test failure occurred upon installation of version
2015.03 of Task::Star (it did not occur with the previous version):

==> Fetching LWP::Simple
==> Building LWP::Simple
Compiling lib/LWP/Simple.pm to mbc
==> Testing LWP::Simple
t/000-load-module.t ............. ok
t/basic-auth.t .................. ok
t/custom-headers-and-content.t .. ok
t/get-binary-camelia.t .......... ok
t/get-chunked-6guts.t ........... ok
t/get-perl6-org.t ............... ok
t/get-unsized.t ................. ok
t/get-w3-latin1-utf8.t .......... ok
t/get-w3-redirect.t ............. ok
t/getstore.t .................... ok
t/parse-url.t ................... ok
Failed to connect: connection timed out
  in method initialize at src/gen/m-CORE.setting:24980
  in method new at src/gen/m-CORE.setting:24964
  in block <unit> at t/socket-sanity.t:6
t/socket-sanity.t ...............
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 2/2 subtests
t/stringify-headers.t ........... ok
Test Summary Report
-------------------
t/socket-sanity.t             (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 2 tests but ran 0.
Files=13, Tests=53, 80 wallclock secs ( 0.04 usr  0.02 sys + 10.79
cusr  0.76 csys = 11.61 CPU)
Result: FAIL
test stage failed for LWP::Simple: Tests failed
  in method install at lib/Panda.pm:125
  in block  at lib/Panda.pm:1
  in method resolve at lib/Panda.pm:185
  in sub MAIN at
/home/tbrowde/.rakudobrew/moar-nom/install/share/perl6/site/bin/panda:20
  in sub MAIN at
/home/tbrowde/.rakudobrew/moar-nom/install/share/perl6/site/bin/panda:18
  in block <unit> at
/home/tbrowde/.rakudobrew/moar-nom/install/share/perl6/site/bin/panda:77

Failure Summary
----------------
Task::Star
*test stage failed for LWP::Simple: Tests failed

**Comment by cosimo** [comment]
Thanks for reporting. I'm happy to note that it's currently working with 2015.09.
