### ISSUE TITLE
Deprecated feature at line 48 in t/parse-url.t

### ISSUE THREAD

**Issue by cschwenz** [cosimo/perl6-lwp-simple#54]
==> Testing LWP::Simple
    [...]
    Saw 1 occurrence of deprecated code.
    ================================================================================
    Sub isa_ok (from Test) seen at:
      t/parse-url.t, line 48
    Deprecated since v2015.5, will be removed with release v2015.9!
    Please use isa-ok instead.
    --------------------------------------------------------------------------------
    Please contact the author to have these occurrences of deprecated code
    adapted, so that this message will disappear!
    
    Please note that *ALL* deprecated features will be removed at the RC-0 release
    (expected September 2015).

**Comment by azawawi** [comment]
This is fixed in https://github.com/cosimo/perl6-lwp-simple/pull/52. Please merge ASAP.

**Comment by cosimo** [comment]
Done.
